-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 16:26:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(45) NOT NULL,
  `lastNames` VARCHAR(45) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `isVerified` TINYINT NOT NULL DEFAULT 0,
  `nickname` VARCHAR(45) NULL,
  `profileImage` VARCHAR(200) NOT NULL,
  `isFreelancer` TINYINT NOT NULL DEFAULT 0,
  `birthDate` DATE NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gig` (
  `idGig` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `Gigcol` VARCHAR(45) NULL,
  `idCategory` INT NOT NULL,
  `idUser` INT NOT NULL,
  `price` INT NOT NULL,
  `deliveryDays` INT NOT NULL,
  PRIMARY KEY (`idGig`, `idCategory`, `idUser`),
  INDEX `fk_Gig_Category_idx` (`idCategory` ASC) VISIBLE,
  INDEX `fk_Gig_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Gig_Category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `mydb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gig_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Language` (
  `idLanguage` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLanguage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Language` (
  `User_idUser` INT NOT NULL,
  `Language_idLanguage` INT NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_idUser`, `Language_idLanguage`),
  INDEX `fk_User_has_Language_Language1_idx` (`Language_idLanguage` ASC) VISIBLE,
  INDEX `fk_User_has_Language_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Language_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Language_Language1`
    FOREIGN KEY (`Language_idLanguage`)
    REFERENCES `mydb`.`Language` (`idLanguage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ability` (
  `idAbility` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAbility`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Ability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Ability` (
  `User_idUser` INT NOT NULL,
  `Ability_idAbility` INT NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_idUser`, `Ability_idAbility`),
  INDEX `fk_User_has_Ability_Ability1_idx` (`Ability_idAbility` ASC) VISIBLE,
  INDEX `fk_User_has_Ability_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Ability_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Ability_Ability1`
    FOREIGN KEY (`Ability_idAbility`)
    REFERENCES `mydb`.`Ability` (`idAbility`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `idReview` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `Gig_idGig` INT NOT NULL,
  `createdAt` VARCHAR(45) NOT NULL,
  `rating` DOUBLE NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idReview`, `User_idUser`, `Gig_idGig`),
  INDEX `fk_Review_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Review_Gig1_idx` (`Gig_idGig` ASC) VISIBLE,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Gig1`
    FOREIGN KEY (`Gig_idGig`)
    REFERENCES `mydb`.`Gig` (`idGig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `status` ENUM('Created', 'Confirmed', 'Delivered', 'Completed') NOT NULL,
  `idUser` INT NOT NULL,
  `idGig` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `idUser`, `idGig`),
  INDEX `fk_Order_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_Order_Gig1_idx` (`idGig` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Gig1`
    FOREIGN KEY (`idGig`)
    REFERENCES `mydb`.`Gig` (`idGig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificate` (
  `idCertificate` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `institution` VARCHAR(45) NOT NULL,
  `year` YEAR NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idCertificate`, `User_idUser`),
  INDEX `fk_Certificate_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Certificate_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;